### ISSUE TITLE
Can't find Dockerfile with non-standard name

### ISSUE THREAD

**Issue by hannesrohde** [sgornostal/gradle-docker-plugin#7]
This issue looks like a follow-up issue to #2 to me:

When a Dockerfile with a non-standard-name is specified, the file is copied to the build-directory but the buildDocker task fails to pick it up:

    docker {
        files jar.archivePath
        dockerFile = 'Dockerfile-gradle'
    }

results in 

    :prepareDocker
    :buildDocker FAILED
    FAILURE: Build failed with an exception.
    * What went wrong:
    Execution failed for task ':buildDocker'.
    > Dockerfile does not exist

even though build/docker/ has both the jar and Dockerfile-gradle

**Comment by sgornostal** [comment]
Fixed in 1.5.4

**Comment by hannesrohde** [comment]
Great, thanks alot for the quick response and solution!
